language: node_js

node_js:
  - "10"

services:
  - docker

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release

script:
  # ban sensitive files
  - npm run test
  - npx ban -- --all

after_success:
  # report coverage
  - cat ./coverage/lcov.info | tee /dev/tty | sed 's/\/app/\./'| npx coveralls

notifications:
  email:
    recipients:
      - xiechao06@gmail.com
